### PR TITLE
Added java file with methods for testing if the number is a palindrom…

### PR DESCRIPTION
**Pull request by alfadelta10010**
Added java file with methods for testing if the number is a palindrome, to check if two numbers are divisible, to calculate factorials, to reverse the passed number and to calculate and store the Fibbonacci series until the limit passed as an argument.

### CODE REVIEW

**Comment by Mohamed-Ayaan358** [comment]
@AlphaDelta1803 you have not asked a maintainer to raise the issue  in issue #1 and hence it will not be reviewed for now

**Comment by mukunddeepak** [comment]
Add the issue fast if you want the boost points!

> Added java file with methods for testing if the number is a palindrome, to check if two numbers are divisible, to calculate factorials, to reverse the passed number and to calculate and store the Fibbonacci series until the limit passed as an argument.

**Comment by alfadelta10010** [comment]
@mukunddeepak I have created an issue
https://github.com/acmpesuecc/code_snips/issues/8#issue-1027607850

**Comment by Mohamed-Ayaan358** [comment]
I am sorry but this PR is far too generic, easy to find themselves and random for these changes to be accepted.

**Pull request closed without merging**
