### PR TITLE
:sparkles: ML Password Strength Classifier

### PR DESCRIPTION
**Pull request by anirudhlakhotia**
Classifies strength of passwords, trained on huge dataset

### CODE REVIEW

**Comment by Mohamed-Ayaan358** [comment]
Raise an issue. @anirudhlakhotia

**Comment by anirudhlakhotia** [comment]
> Raise an issue. @anirudhlakhotia

Generally?
Or on this repo?

**Comment by Mohamed-Ayaan358** [comment]
> Generally? Or on this repo?

On this repo in the issues tab

**Comment by Mohamed-Ayaan358** [comment]
Redo it if you wish but you have not raised an issue

**Pull request closed without merging**
