### PR TITLE
Add frequently used custom hooks

### PR DESCRIPTION
**Pull request by shreyaskaundinya**
Add useResponsiveWindow custom hook
Works on issue #6

### CODE REVIEW

**Comment by Mohamed-Ayaan358** [comment]
I cannot accept this unless you raise an issue @shreyaskaundinya

**Comment by shreyaskaundinya** [comment]
Issue added!

**Comment by Mohamed-Ayaan358** [comment]
!bounty 40

**Comment by ArnavKumar7** [comment]
nice job !!!

**Pull request merged**
