### PR TITLE
Autoencoder classification of Fashion MNIST Data

### LINKED ISSUE #2: To train autoencoders to classify fashion MNIST Data
This code aims to classify fashion MNIST data(This is used as an example).

Obviously can be altered for different data.

### PR DESCRIPTION
**Pull request by RakshithRAcharya**
Closes #2 .....I have also added the data files and the model h5 files for reference...

### CODE REVIEW

**Comment by RakshithRAcharya** [comment]
Hey @Mohamed-Ayaan358 look into it.....tell me if any changes are needed

**Comment by Mohamed-Ayaan358** [comment]
Alright this will be reviewed and be told.

**Comment by Mohamed-Ayaan358** [comment]
Small addition could you perhaps state, where this code can be used in the textarea of the notebook? @RakshithRAcharya

**Comment by RakshithRAcharya** [comment]
Sure

**Comment by RakshithRAcharya** [comment]
Hey @Mohamed-Ayaan358 I have added 2 usecases at the end of the file....is that enough

**Comment by Mohamed-Ayaan358** [comment]
Great work bro and keep coding !

**Comment by Mohamed-Ayaan358** [comment]
!bounty 90

**Comment by Mohamed-Ayaan358** [comment]
!bounty 70

**Pull request merged**
